// Partner prospect seed data - 15+ SI/ISV/Reseller
export const partnerProspectData = [
  {
    name: 'Accenture 埃森哲',
    type: 'SI', region: 'Global',
    description: '全球最大 IT 顧問與系統整合商',
    services: ['Cloud Strategy', 'Migration', 'Managed Services'],
    why_partner: '進入大型企業的關鍵通路，Accenture 台灣團隊積極拓展多雲業務',
    cooperation_type: '策略聯盟',
    status: 'new',
  },
  {
    name: 'Deloitte Digital 勤業眾信',
    type: 'SI', region: 'TW',
    description: '四大會計師事務所之一，數位轉型顧問',
    services: ['Digital Transformation', 'Cloud Advisory'],
    why_partner: '金融業企業客戶資源豐富，可共同推廣 Alibaba 金融雲',
    cooperation_type: '共銷合作',
    status: 'contacted',
  },
  {
    name: 'PwC 資誠',
    type: 'SI', region: 'TW',
    description: '四大會計師事務所，企業諮詢',
    services: ['Cloud Strategy', 'Risk & Compliance'],
    why_partner: '中國業務合規專長與 Alibaba 中國雲定位互補',
    cooperation_type: '顧問合作',
    status: 'new',
  },
  {
    name: 'Wistron Digital Technology',
    type: 'SI', region: 'TW',
    description: '緯創資通旗下數位轉型子公司',
    services: ['System Integration', 'IIoT', 'Cloud'],
    why_partner: '製造業客戶資源，IIoT + Alibaba Cloud 方案',
    cooperation_type: '聯合方案',
    status: 'new',
  },
  {
    name: 'Asus Cloud 華碩雲端',
    type: 'MSP', region: 'TW',
    description: '華碩子公司，企業雲服務',
    services: ['Cloud Hosting', 'Managed Services', 'DR'],
    why_partner: '華碩既有企業客戶轉介 + 台灣在地支援',
    cooperation_type: 'Reseller',
    status: 'new',
  },
  {
    name: 'Nextlink 訊力科技',
    type: 'reseller', region: 'TW',
    description: '台灣專業雲端代理商，多雲專長',
    services: ['Cloud Reselling', 'Support', 'Migration'],
    why_partner: '代理 AWS/Azure 多年，增加 Alibaba 產品線補足中港市場',
    cooperation_type: 'Reseller',
    status: 'interested',
  },
  {
    name: '叡揚資訊 GSS',
    type: 'ISV', region: 'TW',
    description: '台灣領先企業軟體廠商，Vital 系列',
    services: ['ERP', 'Collaboration', 'DevOps Tools'],
    why_partner: '軟體上架 Alibaba Cloud Marketplace，共同銷售',
    cooperation_type: 'Marketplace ISV',
    status: 'new',
  },
  {
    name: '資通電腦 IISI',
    type: 'SI', region: 'TW',
    description: '台灣老牌 SI，政府與金融客戶多',
    services: ['System Integration', 'Financial Systems'],
    why_partner: '金融業客戶資源 + Alibaba 金融雲方案',
    cooperation_type: '共銷合作',
    status: 'new',
  },
  {
    name: 'CHT Security 中華資安',
    type: 'technology', region: 'TW',
    description: '中華電信集團資安子公司',
    services: ['Security', 'SOC', 'Compliance'],
    why_partner: 'Alibaba Cloud 安全產品與 CHT SOC 整合方案',
    cooperation_type: '技術整合',
    status: 'new',
  },
  {
    name: 'Delta Electronics 台達電',
    type: 'technology', region: 'TW',
    description: '全球電力電子領導者，積極布局 ICT',
    services: ['Datacenter Infrastructure', 'Edge Computing'],
    why_partner: '資料中心硬體 + Alibaba Cloud 邊緣運算方案',
    cooperation_type: '技術聯盟',
    status: 'new',
  },
  {
    name: 'Tatung 大同',
    type: 'SI', region: 'TW',
    description: '大同公司 ICT 事業群',
    services: ['System Integration', 'IoT', 'Smart City'],
    why_partner: '政府標案 + 智慧城市專案資源',
    cooperation_type: '聯合投標',
    status: 'hold', status_reason: '需確認競品綁定關係',
  },
  {
    name: 'Dimension Data / NTT Data',
    type: 'SI', region: 'APAC',
    description: 'NTT 集團國際 SI 業務',
    services: ['Cloud', 'Network', 'Managed Services'],
    why_partner: '亞太跨國客戶，Alibaba Cloud 亞太 Region 優勢',
    cooperation_type: '全球策略聯盟',
    status: 'new',
  },
  {
    name: 'HCL Technologies',
    type: 'SI', region: 'APAC',
    description: '印度三大 IT 服務商之一',
    services: ['IT Services', 'Cloud', 'Digital'],
    why_partner: '印度擴張 + 國際客戶資源',
    cooperation_type: 'Global SI',
    status: 'new',
  },
  {
    name: 'Tech Mahindra',
    type: 'SI', region: 'APAC',
    description: '印度領先 IT 服務與 BPO',
    services: ['IT Services', 'Telecom Consulting'],
    why_partner: '電信業客戶資源 + Alibaba Cloud 電信解決方案',
    cooperation_type: 'Global SI',
    status: 'new',
  },
  {
    name: 'iTrue Tech 誠道科技',
    type: 'agency', region: 'TW',
    description: '台灣數位行銷代理商',
    services: ['Digital Marketing', 'E-commerce Solutions'],
    why_partner: '電商與品牌客戶上雲顧問',
    cooperation_type: '行銷夥伴',
    status: 'new',
  },
  {
    name: '凌群電腦 Syscom',
    type: 'SI', region: 'TW',
    description: '台灣老牌 SI，政府標案實力強',
    services: ['System Integration', 'Government Projects'],
    why_partner: '政府與軍工客戶資源，Alibaba 國際版政府合規方案',
    cooperation_type: '聯合投標',
    status: 'new',
  },
  {
    name: 'Netpoleon',
    type: 'reseller', region: 'APAC',
    description: '亞太資安產品代理',
    services: ['Security Distribution', 'Cloud Security'],
    why_partner: 'Alibaba Cloud 安全產品亞太代理',
    cooperation_type: '經銷',
    status: 'new',
  },
];
