// Extended partner prospect data - iGaming, Adult CDN, SEA/HK, AI Infra
export const partnerProspectData2 = [
  // === iGaming Technology Partners ===
  {
    name: 'SoftSwiss',
    type: 'ISV',
    region: 'Global',
    description: '白俄羅斯/馬爾他 iGaming 平台軟體商，服務 400+ 線上賭場，提供交鑰匙博彩解決方案',
    services: ['Casino Platform', 'Sportsbook', 'Payment Integration'],
    why_partner: '旗下客戶大量需要雲端基礎設施；Alibaba 可作為其推薦的首選雲；共同推廣亞太市場',
    cooperation_type: '推薦合作夥伴 + 技術整合',
    status: 'new',
  },
  {
    name: 'EveryMatrix',
    type: 'ISV',
    region: 'Global',
    description: '馬爾他 iGaming B2B 技術平台，提供 CasinoEngine、OddsMatrix 等模組化方案',
    services: ['Casino Engine', 'Sportsbook Platform', 'PAM'],
    why_partner: '亞太區擴張需要合規雲夥伴；客戶需要低延遲亞洲節點；Alibaba 可作為指定雲',
    cooperation_type: '技術整合夥伴',
    status: 'new',
  },
  {
    name: 'Wazdan',
    type: 'ISV',
    region: 'Global',
    description: '波蘭 iGaming 遊戲內容供應商，100+ 款 HTML5 老虎機，亞洲市場積極拓展',
    services: ['Casino Games', 'Content Distribution'],
    why_partner: '遊戲 CDN 分發需要亞太低延遲節點；Alibaba CDN 直接整合',
    cooperation_type: 'CDN 技術合作',
    status: 'new',
  },
  {
    name: 'BetConstruct',
    type: 'ISV',
    region: 'APAC',
    description: '亞美尼亞 iGaming 全棧技術供應商，在亞太有強勁市場',
    services: ['Sportsbook', 'Live Casino', 'Lottery'],
    why_partner: '亞洲業務快速增長，需要 Alibaba 亞太節點；共同開發市場',
    cooperation_type: '合作推廣',
    status: 'new',
  },
  {
    name: 'GambetDC / Amelco',
    type: 'ISV',
    region: 'Global',
    description: '美國/英國體育博彩技術供應商，正積極進軍亞太',
    services: ['Sports Betting Platform', 'Trading'],
    why_partner: '亞太市場雲部署需要在地夥伴；Alibaba 區域優勢互補',
    cooperation_type: '技術部署合作',
    status: 'new',
  },
  // === Adult Content Infrastructure Partners ===
  {
    name: 'BunnyCDN / Bunny.net',
    type: 'reseller',
    region: 'Global',
    description: '歐洲新興 CDN 供應商，大量成人/媒體客戶，以低成本著稱，可能成為 Alibaba CDN 競爭對手或轉介合作',
    services: ['CDN', 'Storage', 'Video Streaming'],
    why_partner: '了解其亞太客戶需求，探索是否可以成為 Alibaba 亞太 CDN 的轉售合作夥伴',
    cooperation_type: '觀察/探索合作',
    status: 'new',
  },
  {
    name: 'StreamWise CDN (Adult Vertical)',
    type: 'reseller',
    region: 'Global',
    description: '專注成人媒體的 CDN 轉售商，服務 500+ 成人平台',
    services: ['CDN Reselling', 'Video Transcoding', 'Storage'],
    why_partner: 'Alibaba CDN 亞太低成本優勢可透過其觸達大量成人平台客戶；轉售合作模式',
    cooperation_type: 'CDN Reseller',
    status: 'new',
  },
  {
    name: 'VSYS.host',
    type: 'reseller',
    region: 'Global',
    description: '荷蘭成人友善主機與 CDN 服務商，服務上千家成人內容網站',
    services: ['Hosting', 'CDN', 'DDoS Protection'],
    why_partner: '可作為 Alibaba CDN 亞太區的成人市場轉售通路',
    cooperation_type: 'Reseller',
    status: 'new',
  },
  // === SEA Technology Partners ===
  {
    name: 'Redington Gulf / Redington APAC',
    type: 'reseller',
    region: 'SEA',
    description: '印度最大 IT 分銷商，東南亞有廣泛通路，代理多家主流雲廠商',
    services: ['IT Distribution', 'Cloud Reselling', 'Enterprise'],
    why_partner: '東南亞企業客戶通路廣；Alibaba Cloud 在 SEA 知名度低，需要本地通路加速',
    cooperation_type: 'Distribution Partner',
    status: 'new',
  },
  {
    name: 'Telkom Indonesia Digital',
    type: 'SI',
    region: 'SEA',
    description: '印尼國家電信公司數位部門，旗下 Telkomsel 超 1.7 億用戶',
    why_partner: '印尼市場最大通路夥伴；Alibaba Indonesia Region 可透過 Telkom 觸達政府與企業',
    services: ['Telco', 'Managed Cloud', 'Enterprise Solutions'],
    cooperation_type: '策略聯盟',
    status: 'new',
  },
  {
    name: 'Advanced Info Service (AIS)',
    type: 'SI',
    region: 'SEA',
    description: '泰國最大電信商，數位服務積極擴張，旗下 AIS PLAY 數位平台',
    why_partner: '泰國市場首選合作夥伴；透過 AIS 觸達泰國企業與 SMB 客戶',
    services: ['Telecom', 'Cloud Services', 'IoT'],
    cooperation_type: '電信雲合作',
    status: 'new',
  },
  {
    name: 'Singtel / NCS',
    type: 'SI',
    region: 'SEA',
    description: '新加坡國家電信公司，旗下 NCS 是東南亞最大 IT 服務商之一',
    why_partner: '新加坡及東南亞政府與大型企業的主要 IT 服務商；Alibaba 多雲合作機會',
    services: ['Managed Services', 'Digital Transformation', 'Government IT'],
    cooperation_type: '通路合作',
    status: 'new',
  },
  {
    name: 'Maxis Business',
    type: 'SI',
    region: 'SEA',
    description: '馬來西亞第二大電信商，企業 IT 服務部門',
    why_partner: '馬來西亞企業市場通路；Alibaba Malaysia Region 可搭配 Maxis 網路提供完整方案',
    services: ['Telecom', 'Cloud', 'Managed Services'],
    cooperation_type: '電信雲合作',
    status: 'new',
  },
  {
    name: 'Crayon Software (APAC)',
    type: 'reseller',
    region: 'APAC',
    description: '挪威雲端軟體授權與管理服務商，亞太有多國據點',
    services: ['Software Licensing', 'Cloud Reselling', 'FinOps'],
    why_partner: '增加 Alibaba 產品線至其多雲組合；FinOps 工具可整合 Alibaba 費用管理',
    cooperation_type: 'Cloud Reseller + FinOps',
    status: 'new',
  },
  // === AI / GPU Infrastructure Partners ===
  {
    name: 'Lambda Labs',
    type: 'technology',
    region: 'Global',
    description: '美國 GPU 雲端服務商，主打 AI 訓練用途，與 NVIDIA 深度合作',
    services: ['GPU Cloud', 'AI Compute'],
    why_partner: '亞太 GPU 需求可導流至 Alibaba Cloud；潛在技術整合或競爭分析',
    cooperation_type: '探索合作',
    status: 'new',
  },
  {
    name: 'CoreWeave',
    type: 'technology',
    region: 'Global',
    description: '美國 GPU 雲端新創，NVIDIA 最大合作夥伴之一，已獲 $7B 融資',
    services: ['GPU Cloud', 'HPC', 'AI Infra'],
    why_partner: '亞太市場尚未完全覆蓋；Alibaba 可作為 CoreWeave 客戶的亞太備援',
    cooperation_type: '互補合作',
    status: 'new',
  },
  {
    name: 'NVIDIA Enterprise Sales (Taiwan/APAC)',
    type: 'technology',
    region: 'APAC',
    description: 'NVIDIA 企業銷售團隊，在台灣與東南亞有專屬 BD 人員',
    services: ['GPU Hardware', 'AI Software Stack', 'DGX Solutions'],
    why_partner: '共同推廣 Alibaba Cloud GPU 實例（使用 NVIDIA 晶片）；聯合行銷 AI 解決方案',
    cooperation_type: '技術聯盟 + 聯合行銷',
    status: 'contacted',
  },
  {
    name: 'AMD Cloud Partner',
    type: 'technology',
    region: 'APAC',
    description: 'AMD 企業級 GPU（Instinct MI300X）推廣團隊，提供 NVIDIA 替代方案',
    services: ['GPU Hardware', 'AI Accelerators'],
    why_partner: 'Alibaba GPU 實例多元化；AMD GPU 對 AI 推理成本效益高；聯合推廣',
    cooperation_type: '技術合作',
    status: 'new',
  },
  // === HK Partners ===
  {
    name: 'Equinix Hong Kong',
    type: 'technology',
    region: 'HK',
    description: '全球最大數位交換中心，香港有多個 IBX 機房，是主要互聯點',
    services: ['Colocation', 'Interconnection', 'Cloud Exchange'],
    why_partner: 'Alibaba 香港 Region 可透過 Equinix HK 直連更多企業客戶；Equinix ECX 整合',
    cooperation_type: '互聯互通',
    status: 'new',
  },
  {
    name: 'CITIC Telecom CPC (香港)',
    type: 'reseller',
    region: 'HK',
    description: '香港 CITIC 旗下電信服務商，專注企業與跨境聯網',
    services: ['SD-WAN', 'Cloud Connectivity', 'China Access'],
    why_partner: '中港跨境專線 + Alibaba China Region 聯合方案；觸達香港企業的中國業務部門',
    cooperation_type: '通路合作',
    status: 'new',
  },
  // === Taiwan Vertical-Specific ===
  {
    name: 'Noodoe (昱沐)',
    type: 'ISV',
    region: 'TW',
    description: '台灣 EV 充電管理 SaaS，在 EV 基礎設施快速擴張',
    services: ['EV Charging SaaS', 'IoT', 'Energy Management'],
    why_partner: '旗下客戶（充電站業者）需要 IoT 雲；Alibaba IoT 平台整合；聯合方案進攻電動車市場',
    cooperation_type: 'ISV 聯合方案',
    status: 'new',
  },
  {
    name: 'Shopline 商線科技',
    type: 'ISV',
    region: 'APAC',
    description: '亞太 SaaS 電商平台，服務 35 萬+ 商家，台港東南亞皆有市場',
    services: ['E-commerce Platform', 'Omnichannel'],
    why_partner: '商家的雲端基礎設施可使用 Alibaba；Alibaba 電商技術整合優勢；共同進攻東南亞電商',
    cooperation_type: 'ISV 合作 + 通路推薦',
    status: 'new',
  },
  {
    name: 'iStar 艾斯達',
    type: 'reseller',
    region: 'TW',
    description: '台灣雲端解決方案代理商，擅長企業雲移轉',
    services: ['Cloud Migration', 'Multi-cloud Management', 'Support'],
    why_partner: '增加 Alibaba 為其代理組合；台灣 SMB 與中型企業通路',
    cooperation_type: 'Reseller',
    status: 'new',
  },
];
