// CN region partner prospect data - 大陸橋接夥伴、台灣涉陸 SI/Reseller
export const partnerProspectDataCN = [
  // === 台灣涉陸 SI / 系統整合商 ===
  {
    name: 'Systex China（精誠中國）',
    type: 'SI',
    region: 'CN',
    description: '精誠資訊大陸子公司，服務台資企業大陸 IT 需求，SAP/Oracle 整合商',
    services: ['ERP Integration', 'Cloud Migration', 'Managed Services'],
    why_partner: '台資企業大陸 IT 主要服務商；可捆綁 Alibaba Cloud 推廣給台資工廠；現有客戶轉介',
    cooperation_type: '台資企業通路',
    status: 'new',
  },
  {
    name: 'Ecolink（宜鼎國際）智慧雲',
    type: 'SI',
    region: 'CN',
    description: '工業儲存硬體商，在大陸有 AIoT 雲端業務，服務製造業客戶',
    services: ['Industrial IoT', 'Edge Computing', 'Smart Factory'],
    why_partner: '製造業 IoT 場景與 Alibaba Industrial Cloud 互補；大陸客戶可導入 Alibaba 雲',
    cooperation_type: 'ISV 聯合方案',
    status: 'new',
  },
  {
    name: 'Microland（中磊電子）Tech Solutions',
    type: 'SI',
    region: 'CN',
    description: '台商在大陸的 IT 服務商，專注工廠自動化與 IT/OT 整合',
    services: ['OT/IT Integration', 'Factory Automation', 'Network'],
    why_partner: '大陸台資製造業 IT 整合商；可透過其推廣 Alibaba 工業 IoT 解決方案',
    cooperation_type: '聯合方案',
    status: 'new',
  },
  // === 香港/大陸 Reseller / MSP ===
  {
    name: 'CITIC Telecom CPC（大陸業務）',
    type: 'reseller',
    region: 'CN',
    description: '中信國際電訊，提供中港跨境專線及大陸雲服務，企業 SD-WAN 市場強',
    services: ['SD-WAN', 'China Connect', 'Cloud Reselling', 'Enterprise Network'],
    why_partner: '中港跨境企業網路 + Alibaba 大陸 Region 聯合方案；觸達香港/大陸企業的跨境需求',
    cooperation_type: '通路合作 + 捆綁銷售',
    status: 'new',
  },
  {
    name: 'ChinaNetCloud（雲畢業）',
    type: 'MSP',
    region: 'CN',
    description: '上海 Alibaba Cloud MSP 合作夥伴，專注電商、零售、遊戲行業雲端管理',
    services: ['Alibaba Cloud MSP', 'Cost Optimization', 'DevOps'],
    why_partner: '已是 Alibaba Cloud 認證 MSP；可透過其觸達大陸中型企業客戶；合作推廣',
    cooperation_type: 'MSP 通路合作',
    status: 'new',
  },
  {
    name: '雲徙科技（CloudWay）',
    type: 'SI',
    region: 'CN',
    description: '大陸零售數位化 SI，阿里巴巴生態系統整合商，服務品牌零售商新零售轉型',
    services: ['Retail Digitalization', 'Alibaba Ecosystem Integration', 'DTC Platform'],
    why_partner: '深度整合阿里巴巴生態；可作為品牌零售客戶進入 Alibaba Cloud 的橋接夥伴',
    cooperation_type: '生態夥伴',
    status: 'new',
  },
  {
    name: 'GreenRabit（綠兔雲）',
    type: 'reseller',
    region: 'CN',
    description: '大陸中小型 Alibaba Cloud 代理商，專注 SEA/跨境電商客戶的雲端需求',
    services: ['Cloud Reselling', 'Cross-border E-commerce Cloud', 'Support'],
    why_partner: '台灣客戶進軍大陸跨境電商的雲端通路；可轉介 Alibaba Cloud 方案',
    cooperation_type: 'Reseller',
    status: 'new',
  },
  // === AI / GPU 大陸生態夥伴 ===
  {
    name: 'NVIDIA China（英偉達中國）',
    type: 'technology',
    region: 'CN',
    description: 'NVIDIA 中國企業銷售團隊，推廣 H20/A800 GPU 及 AI 平台',
    services: ['GPU Hardware', 'AI Software Stack', 'Enterprise AI'],
    why_partner: '聯合推廣 Alibaba Cloud 大陸 GPU 實例；NVIDIA GPU 搭配 Alibaba 雲服務；共同客戶開發',
    cooperation_type: '技術聯盟',
    status: 'new',
  },
  {
    name: '數美科技（Shhumei Tech）',
    type: 'ISV',
    region: 'CN',
    description: '大陸 AI 內容安全領導廠商，服務直播/遊戲/電商平台的違規內容識別',
    services: ['AI Content Moderation', 'Risk Control', 'Live Stream Safety'],
    why_partner: '其客戶（直播/iGaming）正好是 Alibaba Cloud 目標客戶；聯合方案切入直播業者',
    cooperation_type: 'ISV 聯合方案',
    status: 'new',
  },
  {
    name: '雲脈互聯（CloudPulse CN）',
    type: 'technology',
    region: 'CN',
    description: '大陸網路加速技術商，提供跨境專線及 CDN 加速，服務出海企業',
    services: ['Cross-border Network', 'CDN Acceleration', 'SD-WAN'],
    why_partner: '出海企業網路需求 + Alibaba Cloud 國際節點組合；共同觸達大陸出海客戶',
    cooperation_type: '技術整合 + 通路',
    status: 'new',
  },
  // === 大陸金融/企業服務 ===
  {
    name: '金蝶國際（Kingdee）',
    type: 'ISV',
    region: 'CN',
    description: '大陸領先 ERP/雲端企業管理軟體商，服務中大型企業，與阿里有戰略合作',
    services: ['ERP Cloud', 'Financial Cloud', 'HR SaaS'],
    why_partner: '金蝶客戶（中大型企業）正是 Alibaba Cloud 企業雲目標；聯合方案推廣企業數位轉型',
    cooperation_type: 'ISV 戰略合作',
    status: 'new',
  },
  {
    name: '用友網絡（Yonyou）',
    type: 'ISV',
    region: 'CN',
    description: '大陸最大 ERP 廠商，企業數位化轉型 SaaS，與政府/大型國企關係深厚',
    services: ['ERP', 'Financial Management', 'HR Cloud'],
    why_partner: '用友客戶群可接觸 Alibaba Cloud 企業雲；聯合推廣政企雲端轉型方案',
    cooperation_type: '生態夥伴',
    status: 'new',
  },
];
