// Cloud-heavy / AI infrastructure heavy prospect recommendations
// 高度依賴雲端算力、GPU 運算、大頻寬的客戶
export const prospectData6 = [
  // === AI / LLM Companies ===
  {
    company_name: 'Stability AI',
    category: 'cloud_ai',
    region: 'Global',
    description: '英國 AI 新創，Stable Diffusion 開發商，開源圖像生成 AI 龍頭',
    why_alibaba: 'GPU 訓練成本是生死問題；Alibaba Cloud GPU 比 AWS 便宜 20-30%；亞太市場用戶需要就近推理節點',
    estimated_arr: 800000,
    website: 'https://stability.ai',
    headcount: '200+',
    tech_stack: ['AWS', 'NVIDIA A100', 'H100', 'Kubernetes', 'PyTorch'],
    contact_hint: 'VP of Infrastructure / Head of ML Platform',
    status: 'new',
  },
  {
    company_name: 'Midjourney',
    category: 'cloud_ai',
    region: 'Global',
    description: '美國 AI 圖像生成公司，Discord 機器人起家，月活用戶超千萬',
    why_alibaba: 'GPU 推理成本極高；亞太用戶佔比大；需要多供應商 GPU 策略降低依賴',
    estimated_arr: 1200000,
    website: 'https://www.midjourney.com',
    headcount: '50+',
    tech_stack: ['AWS', 'NVIDIA GPU', 'Custom Infrastructure'],
    contact_hint: 'Head of Infrastructure (需透過關係介紹)',
    status: 'new',
  },
  {
    company_name: 'Runway ML',
    category: 'cloud_ai',
    region: 'Global',
    description: '美國 AI 影片生成公司（Gen-2/Gen-3），好萊塢創作者工具，快速成長',
    why_alibaba: '影片生成 GPU 算力極為龐大；多雲策略降低 AWS 依賴；亞太創作者市場增長快',
    estimated_arr: 900000,
    website: 'https://runwayml.com',
    headcount: '200+',
    tech_stack: ['AWS', 'GCP', 'NVIDIA H100', 'PyTorch'],
    contact_hint: 'Head of Platform / VP of Engineering',
    status: 'new',
  },
  {
    company_name: 'Pika Labs',
    category: 'cloud_ai',
    region: 'Global',
    description: 'AI 影片生成新創，與 Runway 競爭，以低成本高品質著稱，已獲大額融資',
    why_alibaba: '快速成長需要彈性 GPU 資源；Alibaba Cloud GPU 性價比高；多區域推理加速',
    estimated_arr: 500000,
    website: 'https://pika.art',
    headcount: '50+',
    tech_stack: ['AWS', 'NVIDIA GPU', 'Kubernetes'],
    contact_hint: 'CTO / Head of Infrastructure',
    status: 'new',
  },
  {
    company_name: 'ElevenLabs',
    category: 'cloud_ai',
    region: 'Global',
    description: 'AI 語音合成龍頭，語音克隆與 TTS 技術領先，亞太多語言市場快速成長',
    why_alibaba: 'GPU 推理成本高；亞太語言模型需要就近部署；客製化語音訓練需要彈性 GPU',
    estimated_arr: 400000,
    website: 'https://elevenlabs.io',
    headcount: '200+',
    tech_stack: ['AWS', 'GCP', 'NVIDIA GPU', 'PyTorch'],
    contact_hint: 'Head of Infrastructure / CTO',
    status: 'new',
  },
  // === AI Startups - APAC ===
  {
    company_name: 'Moonshot AI (月之暗面)',
    category: 'cloud_ai',
    region: 'CN',
    description: '中國 LLM 新創，Kimi Chat 開發者，已獲超 $300M 融資，快速成長',
    why_alibaba: '中國 AI 新創偏好 Alibaba Cloud（本土合規）；大模型訓練需要大量 GPU；海外部署需要多雲',
    estimated_arr: 1500000,
    website: 'https://www.moonshot.cn',
    headcount: '500+',
    tech_stack: ['Alibaba Cloud partial', 'NVIDIA H100', 'A100', 'Kubernetes'],
    contact_hint: 'VP of Engineering / Head of Infrastructure',
    status: 'new',
  },
  {
    company_name: 'MiniMax (稀宇科技)',
    category: 'cloud_ai',
    region: 'CN',
    description: '中國多模態 AI 公司，旗下 Talkie 角色 AI 在全球有大量用戶，已獲騰訊投資',
    why_alibaba: '全球用戶需要多區域部署；AI 推理成本優化；Alibaba GPU 國際區有競爭力',
    estimated_arr: 800000,
    website: 'https://www.minimaxi.com',
    headcount: '500+',
    tech_stack: ['Alibaba Cloud', 'NVIDIA GPU', 'Kubernetes'],
    contact_hint: 'VP of Engineering',
    status: 'new',
  },
  {
    company_name: 'Zhipu AI (智譜 AI)',
    category: 'cloud_ai',
    region: 'CN',
    description: '清華大學孵化的 AI 公司，GLM-4 系列大模型，B 端 API 服務為主',
    why_alibaba: '企業 AI 服務需要合規雲；GPU 算力合作潛力；Alibaba Cloud AI 市集整合機會',
    estimated_arr: 600000,
    website: 'https://zhipuai.cn',
    headcount: '1000+',
    tech_stack: ['Alibaba Cloud', 'NVIDIA GPU', 'Kubernetes'],
    contact_hint: 'CTO / VP of Platform',
    status: 'new',
  },
  {
    company_name: 'DeepSeek',
    category: 'cloud_ai',
    region: 'CN',
    description: '中國 AI 公司（幻方科技旗下），DeepSeek-V3/R1 模型全球影響力，開源策略',
    why_alibaba: '大規模模型訓練需要頂級 GPU 資源；海外推理需要多區域；Alibaba 合作潛力大',
    estimated_arr: 2000000,
    website: 'https://www.deepseek.com',
    headcount: '1000+',
    tech_stack: ['Custom HPC Cluster', 'NVIDIA H800', 'InfiniBand'],
    contact_hint: 'VP of Infrastructure / Head of ML Engineering',
    status: 'new',
  },
  // === Video Processing / Streaming Tech ===
  {
    company_name: 'Mux',
    category: 'cloud_ai',
    region: 'Global',
    description: '美國影片 API 平台，以影片數據分析和串流基礎設施聞名，Netflix/Discord 背後技術',
    why_alibaba: '影片轉碼需要大量 GPU；亞太用戶分發需要低延遲 CDN；多供應商策略',
    estimated_arr: 600000,
    website: 'https://mux.com',
    headcount: '200+',
    tech_stack: ['AWS', 'GCP', 'FFmpeg GPU', 'Kubernetes'],
    contact_hint: 'VP of Engineering / Head of Platform',
    status: 'new',
  },
  {
    company_name: 'Cloudinary',
    category: 'cloud_ai',
    region: 'Global',
    description: '全球最大圖片/影片 CDN 和處理 API 平台，服務超 100 萬開發者',
    why_alibaba: '亞太區圖片處理節點需要擴展；Alibaba Image Processing API 整合潛力；CDN 成本競爭',
    estimated_arr: 700000,
    website: 'https://cloudinary.com',
    headcount: '500+',
    tech_stack: ['AWS', 'GCP', 'Fastly CDN', 'NVIDIA GPU'],
    contact_hint: 'VP of Infrastructure / Head of Cloud',
    status: 'new',
  },
  {
    company_name: 'Agora (声网)',
    category: 'cloud_ai',
    region: 'APAC',
    description: '中國上市即時音視訊 SDK 供應商，TikTok Live / Clubhouse 背後技術',
    why_alibaba: '實時串流需要低延遲全球節點；Alibaba 東南亞節點對 Agora 客戶有優勢；潛在 resell 合作',
    estimated_arr: 800000,
    website: 'https://www.agora.io',
    headcount: '1000+',
    tech_stack: ['AWS', 'Alibaba Cloud partial', 'Custom RTC'],
    contact_hint: 'VP of Infrastructure / Business Development',
    status: 'new',
  },
  // === Crypto / Web3 (高算力需求) ===
  {
    company_name: 'Binance',
    category: 'cloud_ai',
    region: 'Global',
    description: '全球最大加密貨幣交易所，日交易量超 $20B，基礎設施需求龐大',
    why_alibaba: '交易所需要超低延遲；多區域合規部署；AI 風控模型需要 GPU；Alibaba 有加密合規方案',
    estimated_arr: 3000000,
    website: 'https://www.binance.com',
    headcount: '5000+',
    tech_stack: ['AWS', 'GCP', 'Custom DC', 'Kubernetes'],
    contact_hint: 'VP of Infrastructure / CTO (需要高層引薦)',
    status: 'new',
  },
  {
    company_name: 'OKX (OKCoin)',
    category: 'cloud_ai',
    region: 'APAC',
    description: '全球第二大加密貨幣交易所，總部在塞席爾，亞太市場份額大',
    why_alibaba: '亞太交易節點低延遲；多雲架構降低監管風險；AI 量化交易 GPU 需求',
    estimated_arr: 1500000,
    website: 'https://www.okx.com',
    headcount: '3000+',
    tech_stack: ['AWS', 'Alibaba Cloud partial', 'Custom DC'],
    contact_hint: 'VP of Engineering / Head of Infrastructure',
    status: 'new',
  },
  {
    company_name: 'HashKey Group',
    category: 'cloud_ai',
    region: 'HK',
    description: '香港持牌加密資產交易所，是香港唯一持有零售牌照的交易所，快速擴張中',
    why_alibaba: 'Alibaba HK 節點低延遲優勢；金融合規架構；AI 交易風控系統 GPU 需求',
    estimated_arr: 500000,
    website: 'https://www.hashkey.com',
    headcount: '500+',
    tech_stack: ['AWS', 'GCP', 'Kubernetes'],
    contact_hint: 'CTO / Head of Engineering',
    status: 'new',
  },
  // === AI Infra / MLOps ===
  {
    company_name: 'Weights & Biases (W&B)',
    category: 'cloud_ai',
    region: 'Global',
    description: 'MLOps 平台，AI 實驗追蹤工具市場領導者，超 100 萬 AI 工程師使用',
    why_alibaba: '亞太 AI 公司客戶需要就近部署；Alibaba GPU 客戶的 W&B 使用增加；合作 / resell 潛力',
    estimated_arr: 400000,
    website: 'https://wandb.ai',
    headcount: '500+',
    tech_stack: ['GCP', 'AWS', 'Kubernetes'],
    contact_hint: 'VP of Engineering / Head of Infrastructure',
    status: 'new',
  },
  {
    company_name: 'Replicate',
    category: 'cloud_ai',
    region: 'Global',
    description: 'AI 模型部署 API 平台，讓開發者一鍵部署開源 AI 模型，快速成長',
    why_alibaba: 'GPU 算力成本是核心競爭力；亞太用戶需要就近推理；多雲 GPU 策略',
    estimated_arr: 350000,
    website: 'https://replicate.com',
    headcount: '50+',
    tech_stack: ['AWS', 'CoreWeave', 'NVIDIA GPU'],
    contact_hint: 'CTO / Head of Infrastructure',
    status: 'new',
  },
  // === High-traffic Web Platforms ===
  {
    company_name: 'Discord',
    category: 'cloud_ai',
    region: 'Global',
    description: '全球最大遊戲社群平台，月活超 5 億，大量語音/影片/文字即時通訊流量',
    why_alibaba: '亞太區延遲優化需求；CDN 多供應商策略；AI 機器人功能 GPU 需求',
    estimated_arr: 1500000,
    website: 'https://discord.com',
    headcount: '3000+',
    tech_stack: ['GCP', 'Cloudflare', 'Elixir', 'Rust'],
    contact_hint: 'VP of Infrastructure / Head of Platform',
    status: 'new',
  },
  {
    company_name: 'Canva',
    category: 'cloud_ai',
    region: 'APAC',
    description: '澳洲設計 SaaS 獨角獸，月活超 1.7 億，AI 設計功能快速擴張',
    why_alibaba: 'AI 設計功能 GPU 推理成本高；亞太用戶（澳洲、東南亞）需要就近節點；多雲策略',
    estimated_arr: 1200000,
    website: 'https://www.canva.com',
    headcount: '3000+',
    tech_stack: ['AWS', 'GCP', 'NVIDIA GPU', 'Kubernetes'],
    contact_hint: 'VP of Engineering / Head of Cloud',
    status: 'new',
  },
  {
    company_name: 'InVideo AI',
    category: 'cloud_ai',
    region: 'APAC',
    description: '印度 AI 影片創作平台，全球 2500 萬用戶，AI 影片生成快速成長',
    why_alibaba: 'GPU 影片生成成本壓力大；印度 + 東南亞市場適合 Alibaba SEA 節點；成本敏感型客戶',
    estimated_arr: 300000,
    website: 'https://invideo.io',
    headcount: '500+',
    tech_stack: ['AWS', 'GCP', 'NVIDIA GPU', 'FFmpeg'],
    contact_hint: 'CTO / VP of Engineering',
    status: 'new',
  },
];
