// CN region prospect data - 台灣企業大陸業務 + 大陸科技公司
export const prospectDataCN = [
  // === 台灣企業 - 大陸業務需求 ===
  {
    company_name: 'Foxconn（富士康）工業互聯網',
    category: 'enterprise',
    region: 'CN',
    description: '全球最大電子代工廠，鴻海旗下工業互聯網部門，深圳/鄭州廠區數位轉型',
    why_alibaba: '大陸廠區 IoT 數據合規必須在境內雲；Alibaba Cloud 工業 IoT 平台最成熟；與阿里有戰略合作基礎',
    estimated_arr: 2000000,
    website: 'https://www.fii.com.cn',
    headcount: '10000+',
    tech_stack: ['Private Cloud', 'Siemens MindSphere', 'AWS (Global)'],
    contact_hint: 'VP of Digital Transformation / CIO',
    status: 'new',
  },
  {
    company_name: 'ASE Group（日月光半導體）',
    category: 'enterprise',
    region: 'CN',
    description: '全球最大半導體封測廠，大陸廠區（上海、崑山、威海）數位化需求強',
    why_alibaba: '大陸廠區必須用境內合規雲；製造業 AI 品質檢測（Alibaba 視覺 AI）；台灣總部多雲策略',
    estimated_arr: 1500000,
    website: 'https://www.aseglobal.com',
    headcount: '10000+',
    tech_stack: ['SAP', 'AWS (TW)', 'Private DC (CN)'],
    contact_hint: 'IT Director / Head of Smart Manufacturing',
    status: 'new',
  },
  {
    company_name: 'Advantech（研華科技）',
    category: 'enterprise',
    region: 'CN',
    description: '全球工業物聯網龍頭，大陸市場為最大單一市場，深圳/上海/武漢等城市',
    why_alibaba: 'IoT 設備數據上雲需要大陸合規節點；Alibaba IoT Platform + Edge Computing 高度互補；已有部分合作',
    estimated_arr: 800000,
    website: 'https://www.advantech.com',
    headcount: '2000+',
    tech_stack: ['Alibaba Cloud (partial)', 'Azure', 'AWS IoT'],
    contact_hint: 'CTO / VP of IoT Solutions',
    status: 'new',
  },
  {
    company_name: 'Gogoro Network（台灣電動機車）',
    category: 'enterprise',
    region: 'CN',
    description: 'Gogoro 進軍大陸電動車換電網路，與雅迪合作，需要大陸 IoT 雲端基礎設施',
    why_alibaba: '換電站 IoT 數據必須在境內處理（合規要求）；Alibaba Cloud IoT + 電動車行業解決方案；GCP 無中國節點',
    estimated_arr: 600000,
    website: 'https://www.gogoro.com',
    headcount: '1000+',
    tech_stack: ['GCP', 'Kubernetes', 'IoT Hub'],
    contact_hint: 'Head of Cloud Infrastructure / CTO',
    status: 'new',
  },
  {
    company_name: 'Chailease（中租控股）',
    category: 'fintech',
    region: 'CN',
    description: '台灣最大租賃公司，大陸業務（中國中租）規模龐大，Fintech 數位轉型需求',
    why_alibaba: '大陸金融業務必須使用境內合規雲；Alibaba Cloud 金融雲最成熟；大數據徵信需求',
    estimated_arr: 1200000,
    website: 'https://www.chailease.com.tw',
    headcount: '5000+',
    tech_stack: ['IBM', 'Oracle DB', 'Private Cloud (CN)'],
    contact_hint: 'CIO / IT Director China Operations',
    status: 'new',
  },
  // === 大陸科技公司 - 國際擴張需求 ===
  {
    company_name: 'NetEase Games（網易遊戲）',
    category: 'igaming',
    region: 'CN',
    description: '中國第二大遊戲公司，《梦幻西游》《荒野行動》等，積極出海日本/北美/SEA',
    why_alibaba: '出海遊戲需要全球低延遲節點；Alibaba Cloud 國際區有競爭力的遊戲加速方案；已是 Alibaba 大客戶',
    estimated_arr: 3000000,
    website: 'https://www.neteasegames.com',
    headcount: '10000+',
    tech_stack: ['Alibaba Cloud (CN)', 'AWS (Global)', 'CDN multi'],
    contact_hint: 'VP of Infrastructure / Head of Global Ops',
    status: 'new',
  },
  {
    company_name: 'Bilibili（嗶哩嗶哩）',
    category: 'cloud_ai',
    region: 'CN',
    description: '中國最大二次元/年輕人視頻平台，海外用戶快速成長，日本/東南亞擴張中',
    why_alibaba: '海外視頻 CDN 需要低成本亞太節點；Alibaba CDN 亞太覆蓋強；轉碼 GPU 成本優化',
    estimated_arr: 2500000,
    website: 'https://www.bilibili.com',
    headcount: '10000+',
    tech_stack: ['Alibaba Cloud (CN)', 'AWS CloudFront (global)', 'NVIDIA GPU'],
    contact_hint: 'VP of Infrastructure / Head of CDN',
    status: 'new',
  },
  {
    company_name: 'Shein（希音）',
    category: 'ecommerce',
    region: 'CN',
    description: '全球最大快時尚電商，廣州總部，覆蓋 150+ 國，每日 SKU 超 10 萬件',
    why_alibaba: '亞太電商物流需要低延遲 CDN；大量圖片/視頻內容分發；AI 選品推薦算法算力',
    estimated_arr: 5000000,
    website: 'https://www.shein.com',
    headcount: '10000+',
    tech_stack: ['AWS', 'GCP', 'Akamai CDN'],
    contact_hint: 'VP of Cloud Infrastructure / Head of Platform Engineering',
    status: 'new',
  },
  {
    company_name: 'Moonshot AI（月之暗面）',
    category: 'cloud_ai',
    region: 'CN',
    description: '中國 LLM 新創，Kimi Chat 開發者，已獲超 $300M 融資，快速成長',
    why_alibaba: '中國 AI 新創偏好 Alibaba Cloud（本土合規）；大模型訓練需要大量 GPU；海外部署需要多雲',
    estimated_arr: 1500000,
    website: 'https://www.moonshot.cn',
    headcount: '500+',
    tech_stack: ['Alibaba Cloud partial', 'NVIDIA H100', 'A100', 'Kubernetes'],
    contact_hint: 'VP of Engineering / Head of Infrastructure',
    status: 'new',
  },
  {
    company_name: 'DeepSeek（深度求索）',
    category: 'cloud_ai',
    region: 'CN',
    description: '中國 AI 公司（幻方科技旗下），DeepSeek-V3/R1 模型全球影響力，開源策略',
    why_alibaba: '大規模模型訓練需要頂級 GPU 資源；海外推理需要多區域；Alibaba 合作潛力大',
    estimated_arr: 2000000,
    website: 'https://www.deepseek.com',
    headcount: '1000+',
    tech_stack: ['Custom HPC Cluster', 'NVIDIA H800', 'InfiniBand'],
    contact_hint: 'VP of Infrastructure / Head of ML Engineering',
    status: 'new',
  },
  {
    company_name: 'MiniMax（稀宇科技）',
    category: 'cloud_ai',
    region: 'CN',
    description: '中國多模態 AI 公司，旗下 Talkie 角色 AI 在全球有大量用戶，已獲騰訊投資',
    why_alibaba: '全球用戶需要多區域部署；AI 推理成本優化；Alibaba GPU 國際區有競爭力',
    estimated_arr: 800000,
    website: 'https://www.minimaxi.com',
    headcount: '500+',
    tech_stack: ['Alibaba Cloud', 'NVIDIA GPU', 'Kubernetes'],
    contact_hint: 'VP of Engineering',
    status: 'new',
  },
  {
    company_name: 'Zhipu AI（智譜 AI）',
    category: 'cloud_ai',
    region: 'CN',
    description: '清華大學孵化的 AI 公司，GLM-4 系列大模型，B 端 API 服務為主',
    why_alibaba: '企業 AI 服務需要合規雲；GPU 算力合作潛力；Alibaba Cloud AI 市集整合機會',
    estimated_arr: 600000,
    website: 'https://zhipuai.cn',
    headcount: '1000+',
    tech_stack: ['Alibaba Cloud', 'NVIDIA GPU', 'Kubernetes'],
    contact_hint: 'CTO / VP of Platform',
    status: 'new',
  },
  {
    company_name: 'Kuaishou（快手）International',
    category: 'cloud_ai',
    region: 'CN',
    description: '中國短影音平台（快手/Kwai），海外業務 Kwai 在巴西/東南亞快速成長',
    why_alibaba: '海外視頻 CDN 亞太節點需求；大量 AI 推薦算法 GPU；Alibaba 海外 CDN 性價比高',
    estimated_arr: 3000000,
    website: 'https://www.kuaishou.com',
    headcount: '10000+',
    tech_stack: ['Alibaba Cloud (CN)', 'AWS (Global)', 'Custom CDN'],
    contact_hint: 'Head of International Infrastructure / VP Engineering',
    status: 'new',
  },
  {
    company_name: 'Trip.com Group（攜程）',
    category: 'enterprise',
    region: 'CN',
    description: '中國最大在線旅遊平台，2023 年國際業務（Trip.com）佔比大幅提升，東南亞/歐洲用戶成長',
    why_alibaba: '國際業務需要亞太低延遲基礎設施；大量交易數據需要多雲備援；Alibaba 旅遊業解決方案',
    estimated_arr: 2000000,
    website: 'https://www.trip.com',
    headcount: '30000+',
    tech_stack: ['Alibaba Cloud (CN)', 'AWS (Global)', 'Azure (EU)'],
    contact_hint: 'VP of International Infrastructure / CTO Office',
    status: 'new',
  },
  {
    company_name: 'Xiaomi（小米）Cloud Services',
    category: 'enterprise',
    region: 'CN',
    description: '小米智能設備生態系，IoT 設備出貨量全球前三，海外市場印度/歐洲強勁',
    why_alibaba: 'IoT 設備數據上雲（境內合規）；海外設備服務需要 Alibaba 國際 CDN；與阿里有既有合作',
    estimated_arr: 4000000,
    website: 'https://www.mi.com',
    headcount: '30000+',
    tech_stack: ['Alibaba Cloud (partial)', 'AWS (Global)', 'Google Firebase'],
    contact_hint: 'VP of Cloud Infrastructure / Head of IoT Platform',
    status: 'new',
  },
];
