// Prospect recommendation seed data - Part 2: SEA, HK, iGaming
export const prospectData2 = [
  // === Enterprise - SEA/HK ===
  {
    company_name: 'Grab', category: 'enterprise', region: 'SG',
    description: '東南亞最大超級 App，叫車、外送、金融一站式',
    why_alibaba: '高併發 + 多國合規，Alibaba Cloud 在東南亞 6 個國家有 Region，法遵最齊全',
    estimated_arr: 1500000, website: 'https://www.grab.com', headcount: '5000+',
    tech_stack: ['AWS', 'Kubernetes', 'Apache Kafka'], contact_hint: 'VP of Infrastructure',
    status: 'new',
  },
  {
    company_name: 'Gojek', category: 'enterprise', region: 'SEA',
    description: '印尼第一超級 App（與 Tokopedia 合併為 GoTo）',
    why_alibaba: '印尼電商流量大、AI 推薦需求，Alibaba Cloud Jakarta Region 低延遲',
    estimated_arr: 1000000, website: 'https://www.gojek.com', headcount: '5000+',
    tech_stack: ['AWS', 'GCP', 'Kubernetes'], contact_hint: 'Head of Cloud Platform',
    status: 'new',
  },
  {
    company_name: 'Sea Group / Shopee', category: 'ecommerce', region: 'SG',
    description: '東南亞最大電商平台，同時經營 Garena 遊戲、SeaMoney',
    why_alibaba: '電商雙11流量場景完美對應 Alibaba 經驗；GPU 需求大（AI 推薦）',
    estimated_arr: 2000000, website: 'https://www.seagroup.com', headcount: '10000+',
    tech_stack: ['AWS', 'GCP', 'Kubernetes'], contact_hint: 'VP of Engineering',
    status: 'new',
  },
  {
    company_name: 'Tokopedia (GoTo)', category: 'ecommerce', region: 'SEA',
    description: '印尼最大電商，GoTo Group 核心業務',
    why_alibaba: '印尼數據本地化法律，Alibaba Cloud Jakarta Region 合規',
    estimated_arr: 800000, website: 'https://www.tokopedia.com', headcount: '5000+',
    tech_stack: ['GCP', 'AWS'], contact_hint: 'CTO',
    status: 'new',
  },
  {
    company_name: 'Bukalapak', category: 'ecommerce', region: 'SEA',
    description: '印尼第二大電商，下沉市場強勢',
    why_alibaba: '印尼合規 + 價格敏感，Alibaba 印尼節點 + 折扣方案有競爭力',
    estimated_arr: 400000, website: 'https://www.bukalapak.com', headcount: '2000+',
    tech_stack: ['AWS', 'Kubernetes'], contact_hint: 'Head of Infrastructure',
    status: 'new',
  },
  {
    company_name: 'VNG Corporation', category: 'enterprise', region: 'SEA',
    description: '越南最大網路科技公司，Zalo、遊戲、Fintech',
    why_alibaba: '越南數據本地法規嚴格，Alibaba Cloud 與越南電信合作節點',
    estimated_arr: 300000, website: 'https://www.vng.com.vn', headcount: '3000+',
    tech_stack: ['AWS', 'GCP'], contact_hint: 'VP of Infrastructure',
    status: 'new',
  },
  {
    company_name: 'Singtel', category: 'enterprise', region: 'SG',
    description: '新加坡最大電信，東南亞布局最廣',
    why_alibaba: '與 Alibaba Cloud 有戰略合作可能，電信雲互補，企業客戶共銷',
    estimated_arr: 700000, website: 'https://www.singtel.com', headcount: '10000+',
    tech_stack: ['AWS', 'Azure', 'Private Cloud'], contact_hint: 'Head of Enterprise Cloud',
    status: 'interested',
  },
  {
    company_name: 'PCCW HKT', category: 'enterprise', region: 'HK',
    description: '香港最大電信，積極發展 ICT 服務',
    why_alibaba: '香港節點 + 中國出入口優勢，與 PCCW 企業客戶共銷',
    estimated_arr: 500000, website: 'https://www.pccw.com', headcount: '5000+',
    tech_stack: ['AWS', 'Azure'], contact_hint: 'Cloud Services BU Head',
    status: 'new',
  },
  {
    company_name: 'Cathay Pacific 國泰航空', category: 'enterprise', region: 'HK',
    description: '香港最大航空公司，積極數位轉型',
    why_alibaba: '中國大陸航線資料同步需求，Alibaba Cloud 中港專線穩定',
    estimated_arr: 400000, website: 'https://www.cathaypacific.com', headcount: '5000+',
    tech_stack: ['AWS', 'IBM Cloud'], contact_hint: 'CIO',
    status: 'new',
  },
  {
    company_name: 'Razer', category: 'enterprise', region: 'SG',
    description: '遊戲硬體 + 雲遊戲平台，新加坡總部',
    why_alibaba: '雲遊戲需要低延遲全球 CDN，Alibaba Cloud GSLB 全球加速',
    estimated_arr: 350000, website: 'https://www.razer.com', headcount: '2000+',
    tech_stack: ['AWS', 'GCP'], contact_hint: 'Cloud Infrastructure Head',
    status: 'new',
  },

  // === iGaming ===
  {
    company_name: 'BBIN', category: 'igaming', region: 'APAC',
    description: '亞洲最大 iGaming 平台之一，台灣起家',
    why_alibaba: 'iGaming 對亞洲低延遲 CDN 需求極高，Alibaba 菲律賓/柬埔寨節點支援博弈合規',
    estimated_arr: 800000, website: 'https://www.bbin.com', headcount: '1000+',
    tech_stack: ['AWS', 'Cloudflare'], contact_hint: 'Infrastructure VP',
    status: 'new',
  },
  {
    company_name: 'Asia Gaming (AG)', category: 'igaming', region: 'APAC',
    description: '亞洲頂級真人荷官平台',
    why_alibaba: '真人直播需要低延遲串流，Alibaba RTC + 菲律賓節點',
    estimated_arr: 500000, website: 'https://www.agasiagaming.com', headcount: '500+',
    tech_stack: ['AWS', 'CDN.net'], contact_hint: 'Technical Director',
    status: 'new',
  },
  {
    company_name: 'SA Gaming', category: 'igaming', region: 'APAC',
    description: '菲律賓註冊，亞洲市場領先的真人博弈平台',
    why_alibaba: '菲律賓 PAGCOR 合規 + 全亞洲低延遲，Alibaba Manila Region',
    estimated_arr: 400000, website: 'https://www.saglobal77.com', headcount: '500+',
    tech_stack: ['AWS', 'Private CDN'], contact_hint: 'CTO',
    status: 'new',
  },
  {
    company_name: 'Sexy Gaming', category: 'igaming', region: 'APAC',
    description: '亞洲真人荷官直播平台',
    why_alibaba: '直播流量對 CDN 品質敏感，Alibaba CDN 亞洲覆蓋最廣',
    estimated_arr: 300000, website: 'https://www.sexygaming.com', headcount: '300+',
    tech_stack: ['AWS', 'CloudFlare'], contact_hint: 'Head of Engineering',
    status: 'new',
  },
  {
    company_name: 'WM Casino', category: 'igaming', region: 'APAC',
    description: '亞洲在線博弈品牌',
    why_alibaba: 'iGaming 經常被封鎖需要彈性 IP 與防 DDoS，Alibaba Cloud 安全防護強',
    estimated_arr: 250000, website: 'https://www.wm-casino.com', headcount: '200+',
    tech_stack: ['AWS', 'CloudFlare'], contact_hint: 'CTO',
    status: 'new',
  },
  {
    company_name: 'Pragmatic Play', category: 'igaming', region: 'Global',
    description: '全球頂級 iGaming 內容供應商，超過 300 款遊戲',
    why_alibaba: '亞洲市場擴張需要低延遲 CDN，Alibaba 覆蓋最全',
    estimated_arr: 600000, website: 'https://www.pragmaticplay.com', headcount: '1000+',
    tech_stack: ['AWS', 'Azure'], contact_hint: 'Head of Platform',
    status: 'new',
  },
  {
    company_name: 'Evolution Gaming', category: 'igaming', region: 'Global',
    description: '全球最大真人荷官 B2B 供應商（瑞典上市）',
    why_alibaba: '亞洲市場擴張（日本、菲律賓、韓國），Alibaba Region 最齊全',
    estimated_arr: 800000, website: 'https://www.evolution.com', headcount: '10000+',
    tech_stack: ['AWS', 'Azure', 'Private DC'], contact_hint: 'CTO / Head of APAC',
    status: 'new',
  },
  {
    company_name: '888 Holdings', category: 'igaming', region: 'Global',
    description: '全球老牌線上博弈營運商（倫敦上市）',
    why_alibaba: '亞洲市場擴張機會，Alibaba Cloud 博弈產業合規經驗',
    estimated_arr: 500000, website: 'https://www.888holdings.com', headcount: '2000+',
    tech_stack: ['AWS', 'Azure'], contact_hint: 'VP Engineering',
    status: 'new',
  },
  {
    company_name: 'PlayTech', category: 'igaming', region: 'Global',
    description: '全球最大 iGaming 技術平台供應商',
    why_alibaba: '亞洲業務擴張，Alibaba 菲律賓/柬埔寨節點博弈合規',
    estimated_arr: 550000, website: 'https://www.playtech.com', headcount: '6000+',
    tech_stack: ['AWS', 'Azure', 'Oracle'], contact_hint: 'APAC Cloud Lead',
    status: 'new',
  },
  {
    company_name: 'Flutter Entertainment', category: 'igaming', region: 'Global',
    description: '全球最大博弈集團（Paddy Power、Betfair、FanDuel）',
    why_alibaba: '日本、澳洲業務擴張，Alibaba 日本 Region 低延遲',
    estimated_arr: 700000, website: 'https://www.flutter.com', headcount: '20000+',
    tech_stack: ['AWS', 'GCP', 'Azure'], contact_hint: 'Head of Cloud Engineering',
    status: 'hold', status_reason: '優先度較低，先追蹤亞洲拓展計畫',
  },
];
