// Prospect recommendation seed data - Part 3: Adult, Cloud AI, Fintech/Crypto
export const prospectData3 = [
  // === Adult ===
  {
    company_name: 'Aylo (formerly MindGeek)', category: 'adult', region: 'Global',
    description: '全球最大成人影音集團（Pornhub、RedTube、YouPorn 母公司）',
    why_alibaba: '主流雲廠對成人內容政策嚴格，Alibaba Cloud 國際版對合法成人內容更開放；CDN 流量巨大',
    estimated_arr: 2000000, website: 'https://www.aylo.com', headcount: '1000+',
    tech_stack: ['AWS', 'Custom CDN'], contact_hint: 'VP of Infrastructure',
    status: 'new',
  },
  {
    company_name: 'Chaturbate', category: 'adult', region: 'Global',
    description: '全球最大成人直播平台，日均訪問 2 億+',
    why_alibaba: '直播需要全球低延遲 CDN，Alibaba 全球加速網路；亞洲流量佔比提升',
    estimated_arr: 1500000, website: 'https://www.chaturbate.com', headcount: '200+',
    tech_stack: ['AWS', 'Custom streaming'], contact_hint: 'CTO',
    status: 'new',
  },
  {
    company_name: 'LiveJasmin', category: 'adult', region: 'Global',
    description: '全球領先成人直播平台，匈牙利總部',
    why_alibaba: '直播串流品質 + 亞洲市場擴張，Alibaba RTC + 東南亞節點',
    estimated_arr: 800000, website: 'https://www.livejasmin.com', headcount: '500+',
    tech_stack: ['AWS', 'Cloudflare'], contact_hint: 'Head of Engineering',
    status: 'new',
  },
  {
    company_name: 'OnlyFans', category: 'adult', region: 'Global',
    description: '全球最大創作者訂閱平台',
    why_alibaba: '全球流量 + 金流，Alibaba Cloud 有 PCI DSS 合規 + 全球 CDN',
    estimated_arr: 1200000, website: 'https://www.onlyfans.com', headcount: '200+',
    tech_stack: ['AWS', 'Kubernetes'], contact_hint: 'CTO',
    status: 'new',
  },
  {
    company_name: 'Stripchat', category: 'adult', region: 'Global',
    description: '成人直播平台，塞普勒斯註冊',
    why_alibaba: '全球 CDN + 反 DDoS，Alibaba 亞洲節點延遲優勢',
    estimated_arr: 600000, website: 'https://www.stripchat.com', headcount: '100+',
    tech_stack: ['AWS', 'Custom CDN'], contact_hint: 'Head of Infrastructure',
    status: 'new',
  },
  {
    company_name: 'JuicyAds', category: 'adult', region: 'Global',
    description: '成人廣告聯播網',
    why_alibaba: '廣告即時競價需低延遲 + 全球流量，Alibaba Cloud 全球加速',
    estimated_arr: 300000, website: 'https://www.juicyads.com', headcount: '50+',
    tech_stack: ['AWS', 'CloudFlare'], contact_hint: 'CTO',
    status: 'hold', status_reason: '規模較小，先觀察',
  },
  {
    company_name: 'TrafficJunky', category: 'adult', region: 'Global',
    description: 'Aylo 旗下成人廣告網路',
    why_alibaba: '與 Aylo 整體合作機會，Alibaba Cloud 成人內容友善',
    estimated_arr: 400000, website: 'https://www.trafficjunky.com', headcount: '50+',
    tech_stack: ['AWS'], contact_hint: 'Head of Platform',
    status: 'new',
  },

  // === Cloud / AI ===
  {
    company_name: 'Stability AI', category: 'cloud_ai', region: 'Global',
    description: 'Stable Diffusion 開發公司，圖像生成 AI 領導者',
    why_alibaba: 'GPU 訓練成本敏感，Alibaba Cloud A100/H100 GPU 價格比 AWS 便宜 30%',
    estimated_arr: 1000000, website: 'https://stability.ai', headcount: '200+',
    tech_stack: ['AWS', 'GCP', 'NVIDIA GPU'], contact_hint: 'Head of Infrastructure',
    status: 'new',
  },
  {
    company_name: 'Runway ML', category: 'cloud_ai', region: 'Global',
    description: 'AI 影片生成領導者（Gen-3）',
    why_alibaba: '影片生成需要大量 GPU，Alibaba Cloud PAI-EAS 推理平台低成本',
    estimated_arr: 600000, website: 'https://runwayml.com', headcount: '100+',
    tech_stack: ['AWS', 'GCP'], contact_hint: 'CTO',
    status: 'new',
  },
  {
    company_name: 'ElevenLabs', category: 'cloud_ai', region: 'Global',
    description: 'AI 語音合成獨角獸',
    why_alibaba: '亞洲市場擴張，Alibaba Cloud 亞洲節點 + GPU 推理低延遲',
    estimated_arr: 500000, website: 'https://elevenlabs.io', headcount: '150+',
    tech_stack: ['AWS', 'GCP'], contact_hint: 'VP of Engineering',
    status: 'new',
  },
  {
    company_name: 'Character.AI', category: 'cloud_ai', region: 'Global',
    description: 'AI 角色扮演對話平台，估值 50 億美元',
    why_alibaba: '推理成本是主要瓶頸，Alibaba Cloud 自研 AI 晶片倚天 710 成本優勢',
    estimated_arr: 800000, website: 'https://character.ai', headcount: '50+',
    tech_stack: ['GCP'], contact_hint: 'Head of Infrastructure',
    status: 'new',
  },
  {
    company_name: 'Perplexity AI', category: 'cloud_ai', region: 'Global',
    description: 'AI 搜尋引擎，Jensen Huang 投資',
    why_alibaba: '亞洲市場擴張需求，Alibaba Cloud 亞洲低延遲 LLM 推理',
    estimated_arr: 400000, website: 'https://perplexity.ai', headcount: '100+',
    tech_stack: ['AWS', 'Azure'], contact_hint: 'VP Engineering',
    status: 'new',
  },
  {
    company_name: 'Cohere', category: 'cloud_ai', region: 'Global',
    description: '加拿大企業級 LLM 公司',
    why_alibaba: '亞洲企業客戶擴張，Alibaba Cloud 亞洲企業雲市場份額第一',
    estimated_arr: 350000, website: 'https://cohere.com', headcount: '200+',
    tech_stack: ['AWS', 'GCP'], contact_hint: 'Partner Cloud Lead',
    status: 'new',
  },
  {
    company_name: 'Pika Labs', category: 'cloud_ai', region: 'Global',
    description: 'AI 影片生成新創，快速成長',
    why_alibaba: '推理成本敏感 + 亞洲流量多，Alibaba GPU 成本優勢',
    estimated_arr: 200000, website: 'https://pika.art', headcount: '30+',
    tech_stack: ['AWS'], contact_hint: 'CTO',
    status: 'new',
  },
  {
    company_name: 'Luma AI', category: 'cloud_ai', region: 'Global',
    description: 'AI 3D 建模與影片生成',
    why_alibaba: 'GPU 需求大，Alibaba Cloud PAI 平台彈性',
    estimated_arr: 250000, website: 'https://lumalabs.ai', headcount: '50+',
    tech_stack: ['AWS', 'GCP'], contact_hint: 'Head of Engineering',
    status: 'new',
  },

  // === Fintech / Crypto ===
  {
    company_name: 'Binance', category: 'fintech', region: 'Global',
    description: '全球最大加密貨幣交易所',
    why_alibaba: '高頻交易需超低延遲 + 全球 Region，Alibaba Cloud 亞洲覆蓋第一',
    estimated_arr: 2500000, website: 'https://www.binance.com', headcount: '8000+',
    tech_stack: ['AWS', 'GCP', 'Private Cloud'], contact_hint: 'CTO / Head of Cloud',
    status: 'new',
  },
  {
    company_name: 'OKX', category: 'fintech', region: 'Global',
    description: '全球前三加密交易所，馬來西亞營運總部',
    why_alibaba: '低延遲交易 + 亞洲合規，Alibaba Cloud 香港/新加坡/日本節點',
    estimated_arr: 1500000, website: 'https://www.okx.com', headcount: '3000+',
    tech_stack: ['AWS', 'GCP'], contact_hint: 'VP Engineering',
    status: 'new',
  },
  {
    company_name: 'Bybit', category: 'fintech', region: 'Global',
    description: '全球前五加密交易所，杜拜總部',
    why_alibaba: '亞洲用戶為主，Alibaba Cloud 亞洲低延遲 + 反 DDoS',
    estimated_arr: 1000000, website: 'https://www.bybit.com', headcount: '2000+',
    tech_stack: ['AWS', 'CloudFlare'], contact_hint: 'Head of Cloud Infrastructure',
    status: 'new',
  },
  {
    company_name: 'MEXC', category: 'fintech', region: 'APAC',
    description: '亞洲最大加密交易所之一',
    why_alibaba: '亞洲流量為主，Alibaba Cloud 延遲與頻寬優勢',
    estimated_arr: 700000, website: 'https://www.mexc.com', headcount: '1500+',
    tech_stack: ['AWS'], contact_hint: 'CTO',
    status: 'new',
  },
  {
    company_name: 'KuCoin', category: 'fintech', region: 'APAC',
    description: '新加坡加密交易所，亞洲使用者眾多',
    why_alibaba: 'Alibaba Cloud 新加坡節點低延遲 + 反 DDoS 防護',
    estimated_arr: 600000, website: 'https://www.kucoin.com', headcount: '1000+',
    tech_stack: ['AWS', 'CloudFlare'], contact_hint: 'Head of Platform',
    status: 'new',
  },
  {
    company_name: 'Kraken', category: 'fintech', region: 'Global',
    description: '美國老牌加密交易所',
    why_alibaba: '亞洲擴張機會，Alibaba Cloud 日本/新加坡合規',
    estimated_arr: 500000, website: 'https://www.kraken.com', headcount: '2000+',
    tech_stack: ['AWS', 'GCP'], contact_hint: 'APAC IT Head',
    status: 'hold', status_reason: '目前無亞洲擴張公開計畫',
  },
  {
    company_name: 'LINE Pay', category: 'fintech', region: 'APAC',
    description: 'LINE 集團支付平台，台日泰皆有業務',
    why_alibaba: '支付高可用 + 亞洲多國合規，Alibaba 金融雲案例多',
    estimated_arr: 400000, website: 'https://pay.line.me', headcount: '1000+',
    tech_stack: ['AWS', 'GCP'], contact_hint: 'Head of Cloud Platform',
    status: 'new',
  },
  {
    company_name: 'JKOPay 街口支付', category: 'fintech', region: 'TW',
    description: '台灣最大第三方支付之一',
    why_alibaba: '金融合規 + AI 反詐欺需求，Alibaba 金融雲方案',
    estimated_arr: 200000, website: 'https://www.jkopay.com', headcount: '500+',
    tech_stack: ['AWS', 'Azure'], contact_hint: 'CTO',
    status: 'new',
  },
  {
    company_name: 'XREX', category: 'fintech', region: 'TW',
    description: '台灣區塊鏈金融科技獨角獸',
    why_alibaba: '跨境支付 + 區塊鏈節點，Alibaba Cloud BaaS 區塊鏈即服務',
    estimated_arr: 150000, website: 'https://www.xrex.io', headcount: '200+',
    tech_stack: ['AWS', 'GCP'], contact_hint: 'CTO',
    status: 'interested',
  },
];
