// Prospect recommendation seed data - 50+ companies across all categories
export const prospectData = [
  // === Enterprise - Taiwan ===
  {
    company_name: 'MediaTek 聯發科', category: 'enterprise', region: 'TW',
    description: '全球前三大半導體公司，AI 晶片與 5G 基頻領導者',
    why_alibaba: 'AI 訓練 GPU 需求大增，Alibaba PAI 平台 GPU 成本比 AWS 低 25%；進軍中國大陸市場需要合規雲',
    estimated_arr: 800000, website: 'https://www.mediatek.com', headcount: '5000+',
    tech_stack: ['AWS', 'GCP', 'Kubernetes', 'NVIDIA GPU'], contact_hint: 'Infrastructure VP 或 AI 研發副總',
    status: 'new',
  },
  {
    company_name: 'Foxconn 鴻海', category: 'enterprise', region: 'TW',
    description: '全球最大電子代工，布局電動車、AI 伺服器製造',
    why_alibaba: 'IIoT 工廠數據需求龐大，Alibaba Cloud IoT 平台有製造業參考案例；中國廠區合規需求明確',
    estimated_arr: 1200000, website: 'https://www.foxconn.com', headcount: '10000+',
    tech_stack: ['Azure', 'On-prem', 'SAP'], contact_hint: 'CIO / Digital Transformation Lead',
    status: 'new',
  },
  {
    company_name: 'Quanta 廣達', category: 'enterprise', region: 'TW',
    description: 'AI 伺服器 ODM 龍頭，NVIDIA GB200 主要供應商',
    why_alibaba: '自家 AI 伺服器業務需要內部雲測試平台，Alibaba Cloud GPU 彈性租用適合研發',
    estimated_arr: 600000, website: 'https://www.quantatw.com', headcount: '5000+',
    tech_stack: ['AWS', 'On-prem', 'NVIDIA'], contact_hint: 'Cloud Architecture Head',
    status: 'new',
  },
  {
    company_name: 'Wistron 緯創', category: 'enterprise', region: 'TW',
    description: '全球前五電子代工，AI 伺服器與醫療科技擴張',
    why_alibaba: '緯創醫療需要 HIPAA 合規雲，Alibaba Cloud 多區域合規認證齊全',
    estimated_arr: 450000, website: 'https://www.wistron.com', headcount: '5000+',
    tech_stack: ['Azure', 'On-prem'], contact_hint: 'VP of IT',
    status: 'new',
  },
  {
    company_name: 'Cathay Financial 國泰金控', category: 'fintech', region: 'TW',
    description: '台灣最大金控公司之一，數位轉型積極',
    why_alibaba: '金融業反詐欺 AI 模型訓練需要高效能 GPU，Alibaba Cloud 金融雲有台灣合規方案',
    estimated_arr: 700000, website: 'https://www.cathayholdings.com', headcount: '10000+',
    tech_stack: ['Azure', 'IBM Cloud', 'On-prem'], contact_hint: 'CIO / Digital Banking Lead',
    status: 'new',
  },
  {
    company_name: 'Fubon Financial 富邦金控', category: 'fintech', region: 'TW',
    description: '台灣領先金控，積極布局東南亞市場',
    why_alibaba: '東南亞擴張需要當地雲節點，Alibaba 在馬來西亞、印尼、菲律賓皆有 Region',
    estimated_arr: 600000, website: 'https://www.fubon.com', headcount: '10000+',
    tech_stack: ['AWS', 'Azure'], contact_hint: 'Head of Cloud Infrastructure',
    status: 'new',
  },
  {
    company_name: 'CTBC Bank 中國信託', category: 'fintech', region: 'TW',
    description: '台灣最大民營銀行，海外布局積極',
    why_alibaba: '跨境支付與 RegTech 需求，Alibaba Cloud 有中國合規與東南亞金融雲解決方案',
    estimated_arr: 500000, website: 'https://www.ctbcbank.com', headcount: '10000+',
    tech_stack: ['Azure', 'IBM Cloud'], contact_hint: 'Digital Banking CTO',
    status: 'new',
  },
  {
    company_name: 'Far EasTone 遠傳電信', category: 'enterprise', region: 'TW',
    description: '台灣三大電信，積極發展企業雲與 5G B2B',
    why_alibaba: '電信業 5G Edge Computing 合作，Alibaba Cloud 邊緣運算平台與遠傳既有資源互補',
    estimated_arr: 400000, website: 'https://www.fetnet.net', headcount: '5000+',
    tech_stack: ['AWS', 'Azure', 'VMware'], contact_hint: 'Cloud BU Head',
    status: 'interested',
  },
  {
    company_name: 'Taiwan Mobile 台灣大哥大', category: 'enterprise', region: 'TW',
    description: '台灣電信業者，積極整合 momo 電商',
    why_alibaba: 'momo 電商流量尖峰需要彈性擴容，Alibaba Cloud 電商場景經驗豐富（雙11）',
    estimated_arr: 450000, website: 'https://www.taiwanmobile.com', headcount: '5000+',
    tech_stack: ['AWS', 'Azure'], contact_hint: 'momo IT Head',
    status: 'new',
  },
  {
    company_name: '91APP', category: 'ecommerce', region: 'TW',
    description: '台灣最大 SaaS 電商平台，服務超過 40000 店家',
    why_alibaba: 'AI 個人化推薦需要 GPU，Alibaba Cloud PAI 成本優勢，且東南亞擴張需要 Region',
    estimated_arr: 300000, website: 'https://www.91app.com', headcount: '500-1000',
    tech_stack: ['AWS', 'Kubernetes', 'Redis'], contact_hint: 'CTO',
    status: 'new',
  },
];
