// Adult Content & Entertainment platform prospect recommendations
// These are legitimate businesses with large cloud infrastructure needs
// (高頻寬 CDN、大容量存儲、影片轉碼、DDoS 防護)
export const prospectData5 = [
  // === Adult Content Platforms - Global ===
  {
    company_name: 'Aylo (formerly MindGeek)',
    category: 'adult',
    region: 'Global',
    description: '全球最大成人內容平台集團，旗下 Pornhub、Brazzers、Reality Kings 等，月流量超 30 億次',
    why_alibaba: 'CDN 流量極大需要多雲降低成本；影片轉碼需要大量 GPU；亞太區流量不可忽視；DDoS 防護需求強烈',
    estimated_arr: 2000000,
    website: 'https://aylo.com',
    headcount: '1000+',
    tech_stack: ['AWS', 'Cloudflare', 'Akamai', 'Custom CDN'],
    contact_hint: 'VP of Engineering / Head of Infrastructure',
    status: 'new',
  },
  {
    company_name: 'OnlyFans (Fenix International)',
    category: 'adult',
    region: 'Global',
    description: '英國創作者訂閱平台，2023 年營收超 $6B，以成人內容創作者為主要客群',
    why_alibaba: '影片上傳與分發 CDN 高峰需求；付費牆系統需要高可用；大量用戶資料存儲；亞太市場擴張',
    estimated_arr: 1500000,
    website: 'https://onlyfans.com',
    headcount: '1000+',
    tech_stack: ['AWS', 'CloudFront', 'RDS', 'Elasticsearch'],
    contact_hint: 'CTO / Head of Platform',
    status: 'new',
  },
  {
    company_name: 'Fansly',
    category: 'adult',
    region: 'Global',
    description: 'OnlyFans 最大競爭對手，成長最快的創作者訂閱平台，2022-2023 年用戶成長 10 倍',
    why_alibaba: '快速成長需要彈性雲架構；CDN 多供應商策略降低風險；影片存儲成本壓力大',
    estimated_arr: 600000,
    website: 'https://fansly.com',
    headcount: '200+',
    tech_stack: ['AWS', 'Cloudflare', 'S3'],
    contact_hint: 'CTO / VP of Engineering',
    status: 'new',
  },
  {
    company_name: 'AdultTime / Gamma Entertainment',
    category: 'adult',
    region: 'Global',
    description: '加拿大成人串流平台，訂閱制，擁有數萬支影片內容庫，以高畫質 4K 為賣點',
    why_alibaba: '4K 影片存儲與串流需要大頻寬低延遲 CDN；影片轉碼 GPU 需求；訂閱系統高可用',
    estimated_arr: 400000,
    website: 'https://adulttime.com',
    headcount: '200+',
    tech_stack: ['AWS', 'Akamai', 'FFmpeg GPU'],
    contact_hint: 'CTO / Head of Technology',
    status: 'new',
  },
  {
    company_name: 'AEBN (Adult Entertainment Broadcast Network)',
    category: 'adult',
    region: 'Global',
    description: '美國最大 VOD 成人內容批發商，為數千家網站提供內容授權與分發服務',
    why_alibaba: '內容分發需要全球 CDN；大容量影片庫存儲需求；多客戶端接入高可用',
    estimated_arr: 300000,
    website: 'https://aebn.com',
    headcount: '100+',
    tech_stack: ['AWS', 'CDN', 'Custom Streaming'],
    contact_hint: 'CTO / VP of Technology',
    status: 'new',
  },
  // === Asian Adult Content / Live Streaming ===
  {
    company_name: 'CAM4 / BVN Media',
    category: 'adult',
    region: 'Global',
    description: '全球第四大成人直播平台，月獨立訪客超 1 億，以免費直播模式為主',
    why_alibaba: '直播 CDN 需要亞太低延遲節點；WebRTC 串流架構；大量並發直播房間管理',
    estimated_arr: 500000,
    website: 'https://www.cam4.com',
    headcount: '200+',
    tech_stack: ['AWS', 'CloudFront', 'WebRTC', 'Redis'],
    contact_hint: 'CTO / Head of Streaming Infrastructure',
    status: 'new',
  },
  {
    company_name: 'Stripchat',
    category: 'adult',
    region: 'Global',
    description: '全球前五大成人直播平台，增長最快，2023 年月流量超 5 億，特別強調 VR 直播',
    why_alibaba: 'VR 串流需要超高頻寬 CDN；亞太用戶比例高；直播互動需要低延遲架構',
    estimated_arr: 600000,
    website: 'https://stripchat.com',
    headcount: '300+',
    tech_stack: ['AWS', 'Akamai', 'WebRTC', 'FFmpeg'],
    contact_hint: 'CTO / VP of Infrastructure',
    status: 'new',
  },
  {
    company_name: '17+1 Adult Live Platform (HK-based)',
    category: 'adult',
    region: 'HK',
    description: '香港成人直播平台集團，在港台澳有一定市場，近期積極拓展東南亞',
    why_alibaba: 'Alibaba HK 節點低延遲；直播 CDN 成本壓力；東南亞擴張需要 SEA 節點',
    estimated_arr: 200000,
    website: '',
    headcount: '100+',
    tech_stack: ['Tencent Cloud', 'AWS', 'CDN'],
    contact_hint: 'CTO / CEO',
    status: 'new',
  },
  {
    company_name: 'MYFANS Japan',
    category: 'adult',
    region: 'APAC',
    description: '日本創作者訂閱平台，成人內容為主要品類，服務數萬名日本創作者',
    why_alibaba: '日本市場需要本地合規；影片存儲與分發；支付整合需要多區域架構',
    estimated_arr: 250000,
    website: 'https://myfans.jp',
    headcount: '50+',
    tech_stack: ['AWS', 'CloudFront', 'S3'],
    contact_hint: 'CTO / Head of Engineering',
    status: 'new',
  },
  // === Adjacent: Adult-adjacent Entertainment (Live Streaming with adult content) ===
  {
    company_name: 'Uplive (Asia Innovations Group)',
    category: 'adult',
    region: 'APAC',
    description: '香港社交直播平台，在中東、南亞、東南亞有大量用戶，部分帶有互動娛樂性質',
    why_alibaba: '中東與南亞直播 CDN；Alibaba 中東節點（沙烏地）優勢；直播互動低延遲',
    estimated_arr: 400000,
    website: 'https://www.uplive.sg',
    headcount: '500+',
    tech_stack: ['AWS', 'Alibaba Cloud partial', 'CDN'],
    contact_hint: 'VP of Engineering / CTO',
    status: 'new',
  },
  {
    company_name: 'SugarDaddy Meet / WhatsYourPrice',
    category: 'adult',
    region: 'Global',
    description: '美國社交約會平台集團，面向成人用戶，全球會員超百萬',
    why_alibaba: '用戶資料隱私合規；多區域部署降低法律風險；CDN 加速全球訪問',
    estimated_arr: 150000,
    website: 'https://www.sugardaddymeet.com',
    headcount: '50+',
    tech_stack: ['AWS', 'CloudFront'],
    contact_hint: 'CTO',
    status: 'new',
  },
  {
    company_name: 'TrafficJunky / Aylo Media',
    category: 'adult',
    region: 'Global',
    description: '全球最大成人廣告網路，隸屬 Aylo 集團，每月廣告展示超 300 億次',
    why_alibaba: '廣告投遞需要超低延遲；大量競價請求（RTB）需要高性能計算；亞太廣告主需要亞洲節點',
    estimated_arr: 800000,
    website: 'https://www.trafficjunky.com',
    headcount: '200+',
    tech_stack: ['Custom DC', 'Cloudflare', 'CDN'],
    contact_hint: 'VP of Engineering',
    status: 'new',
  },
  // === Adult Content CDN Resellers & Infrastructure ===
  {
    company_name: 'BunnyCDN / Bunny.net',
    category: 'adult',
    region: 'Global',
    description: '歐洲新興 CDN 供應商，大量成人內容平台客戶，以成本低廉著稱',
    why_alibaba: 'Bunny 是 Alibaba CDN 潛在合作/競爭對象；了解其客戶群可以找切入機會；Alibaba CDN 亞太成本更低',
    estimated_arr: 200000,
    website: 'https://bunny.net',
    headcount: '50+',
    tech_stack: ['Custom CDN', 'On-prem PoP'],
    contact_hint: 'CEO / CTO',
    status: 'new',
  },
  {
    company_name: 'Adult Content Platform SEA (Anonymous)',
    category: 'adult',
    region: 'SEA',
    description: '東南亞在地成人娛樂平台，以泰語、印尼語為主要服務語言，月訪客 2000 萬+',
    why_alibaba: '東南亞本地 CDN 低延遲需求；Alibaba 印尼 + 泰國節點優勢；成本敏感，需要高性價比方案',
    estimated_arr: 180000,
    website: '',
    headcount: '30+',
    tech_stack: ['Vultr', 'Cloudflare', 'S3-compatible'],
    contact_hint: 'CTO / 技術負責人（需要合適引薦人）',
    status: 'new',
  },
  {
    company_name: 'Hotmart (Brazil)',
    category: 'adult',
    region: 'Global',
    description: '巴西最大數位內容銷售平台，涵蓋各類創作者課程與訂閱內容（包含成人品類）',
    why_alibaba: '拉丁美洲 + 亞太雙向擴張；高頻寬影片分發需求；創作者內容全球 CDN',
    estimated_arr: 350000,
    website: 'https://www.hotmart.com',
    headcount: '1000+',
    tech_stack: ['AWS', 'CloudFront', 'Kubernetes'],
    contact_hint: 'CTO / Head of Platform',
    status: 'new',
  },
];
