// iGaming & Online Gambling prospect recommendations
export const prospectData4 = [
  // === iGaming - Global Tier-1 Operators & Software Providers ===
  {
    company_name: 'Evolution Gaming',
    category: 'igaming',
    region: 'Global',
    description: '全球最大真人荷官 Live Casino 供應商，2023 年營收超過 €1.7B，服務全球數百家博彩平台',
    why_alibaba: '真人直播需要亞太區超低延遲 CDN；龐大影片存儲與轉碼需求；大量 WebRTC 流量；亞太玩家佔比高需要就近接入點',
    estimated_arr: 1500000,
    website: 'https://www.evolution.com',
    headcount: '10000+',
    tech_stack: ['AWS', 'Akamai', 'WebRTC', 'CDN', 'NVIDIA GPU'],
    contact_hint: 'VP of Technology / Head of Platform Engineering',
    status: 'new',
  },
  {
    company_name: 'Pragmatic Play',
    category: 'igaming',
    region: 'Global',
    description: '馬爾他 iGaming 內容供應商，旗下 200+ 款老虎機與真人荷官遊戲',
    why_alibaba: '遊戲內容需要全球低延遲分發；亞洲市場快速擴張需要亞太 CDN；遊戲 RNG 伺服器需要高可用架構',
    estimated_arr: 600000,
    website: 'https://www.pragmaticplay.com',
    headcount: '2000+',
    tech_stack: ['AWS', 'CloudFront', 'RDS', 'Redis'],
    contact_hint: 'CTO / Head of Infrastructure',
    status: 'new',
  },
  {
    company_name: 'Playtech',
    category: 'igaming',
    region: 'Global',
    description: '全球最大上市 iGaming 技術供應商（倫敦上市），旗下涵蓋老虎機、真人荷官、體育博彩',
    why_alibaba: '多產品線需要高度可擴展基礎架構；亞太市場擴張（菲律賓 PAGCOR 授權）；高頻交易型態需要低延遲資料庫',
    estimated_arr: 1200000,
    website: 'https://www.playtech.com',
    headcount: '7000+',
    tech_stack: ['Azure', 'AWS', 'Oracle DB', 'Kubernetes'],
    contact_hint: 'Chief Technology Officer / VP of Cloud',
    status: 'new',
  },
  {
    company_name: '888 Holdings',
    category: 'igaming',
    region: 'Global',
    description: '直布羅陀上市大型綜合博彩集團，旗下 888casino、888sport、888poker',
    why_alibaba: '全球多品牌運營需要彈性雲架構；亞太市場新拓展；即時賠率計算需要低延遲計算資源',
    estimated_arr: 800000,
    website: 'https://www.888holdings.com',
    headcount: '5000+',
    tech_stack: ['AWS', 'On-prem', 'Kafka', 'Cassandra'],
    contact_hint: 'Group CTO / Director of Engineering',
    status: 'new',
  },
  {
    company_name: 'Kindred Group (Unibet)',
    category: 'igaming',
    region: 'Global',
    description: '馬爾他上市大型博彩集團，旗下 Unibet、32Red、Maria Casino 等 9 個品牌',
    why_alibaba: '多品牌統一雲遷移；亞太市場新佈局；機器學習負責任博彩系統需要 GPU 資源',
    estimated_arr: 700000,
    website: 'https://www.kindredgroup.com',
    headcount: '5000+',
    tech_stack: ['AWS', 'GCP', 'Spark', 'ML'],
    contact_hint: 'Head of Platform / CTO',
    status: 'new',
  },
  // === iGaming - Asia-Pacific Focused ===
  {
    company_name: 'BBIN (BB Entertainment)',
    category: 'igaming',
    region: 'APAC',
    description: '亞洲最大博彩系統供應商之一，平台上有超過 300 家代理商，深耕亞洲市場',
    why_alibaba: '亞太多節點需求完美符合 Alibaba 佈局；中國玩家接入需要解決方案；高峰流量彈性擴展',
    estimated_arr: 900000,
    website: 'https://www.bbin.com',
    headcount: '1000+',
    tech_stack: ['Alibaba Cloud partial', 'AWS', 'CDN', 'MySQL'],
    contact_hint: 'VP Technology / Infrastructure Director',
    status: 'new',
  },
  {
    company_name: 'Asia Gaming (AG)',
    category: 'igaming',
    region: 'APAC',
    description: '亞洲知名真人荷官解決方案供應商，以百家樂、龍虎等亞洲博彩產品為主',
    why_alibaba: '真人直播需要中港台低延遲 CDN；Alibaba 亞太節點覆蓋最廣；視訊轉碼 GPU 需求',
    estimated_arr: 500000,
    website: 'https://www.asiagaming.com',
    headcount: '500+',
    tech_stack: ['AWS', 'Tencent Cloud', 'CDN'],
    contact_hint: 'CTO / Head of Technology',
    status: 'new',
  },
  {
    company_name: 'GG Poker (GGNetwork)',
    category: 'igaming',
    region: 'Global',
    description: '全球第二大線上撲克平台，以亞洲玩家為主要市場，2023 年流量超越 PokerStars',
    why_alibaba: '亞太區玩家佔多數，需要低延遲遊戲伺服器；高峰賽事需要彈性算力；反作弊 AI 需要 GPU',
    estimated_arr: 600000,
    website: 'https://ggpoker.com',
    headcount: '1000+',
    tech_stack: ['AWS', 'Cloudflare', 'Redis', 'PostgreSQL'],
    contact_hint: 'VP of Engineering / Infrastructure Lead',
    status: 'new',
  },
  {
    company_name: 'Natural8 (ggNetwork)',
    category: 'igaming',
    region: 'APAC',
    description: 'GGNetwork 旗下亞太區主要撲克平台，台港澳及東南亞市場領導品牌',
    why_alibaba: '台灣、香港、東南亞玩家接入優化；Alibaba CDN 亞太節點密集；DDOS 防護需求高',
    estimated_arr: 300000,
    website: 'https://www.natural8.com',
    headcount: '200+',
    tech_stack: ['AWS', 'Cloudflare', 'Redis'],
    contact_hint: 'CTO / Head of Platform',
    status: 'new',
  },
  {
    company_name: 'Fun88',
    category: 'igaming',
    region: 'APAC',
    description: '亞洲知名體育博彩與娛樂場品牌，贊助多支英超足球隊',
    why_alibaba: '亞洲體育直播串流 CDN 需求；賽事期間流量峰值處理；多幣種支付需要多區域部署',
    estimated_arr: 400000,
    website: 'https://www.fun88.com',
    headcount: '500+',
    tech_stack: ['AWS', 'Akamai', 'MySQL Cluster'],
    contact_hint: 'Head of Technology / Director of IT',
    status: 'new',
  },
  {
    company_name: '1xBet',
    category: 'igaming',
    region: 'Global',
    description: '全球增長最快的體育博彩運營商之一，在 50+ 國家有授權，亞洲市場積極擴張',
    why_alibaba: '快速全球擴張需要多區域雲；東南亞流量激增；直播串流與賠率引擎需要低延遲',
    estimated_arr: 800000,
    website: 'https://1xbet.com',
    headcount: '5000+',
    tech_stack: ['AWS', 'Hetzner', 'On-prem', 'CDN'],
    contact_hint: 'CTO / VP of Infrastructure',
    status: 'new',
  },
  {
    company_name: 'Pinnacle',
    category: 'igaming',
    region: 'Global',
    description: '全球知名高賠率體育博彩平台，以職業賭客為目標客群',
    why_alibaba: '賠率引擎需要超低延遲交易處理；亞太玩家比例高；高頻資料更新需要高性能資料庫',
    estimated_arr: 350000,
    website: 'https://www.pinnacle.com',
    headcount: '200+',
    tech_stack: ['AWS', 'PostgreSQL', 'Redis'],
    contact_hint: 'CTO',
    status: 'new',
  },
  {
    company_name: 'Bet365',
    category: 'igaming',
    region: 'Global',
    description: '全球最大私人線上博彩公司，年收入超 £3B，亞洲市場份額龐大',
    why_alibaba: '亞太區玩家接入優化；賽事直播 CDN 需求超大；高可用架構討論（目前主要自建）',
    estimated_arr: 2000000,
    website: 'https://www.bet365.com',
    headcount: '5000+',
    tech_stack: ['Private Cloud', 'On-prem', 'CDN'],
    contact_hint: 'CTO / Head of Infrastructure (需透過關係介紹)',
    status: 'new',
  },
  {
    company_name: 'CMD368',
    category: 'igaming',
    region: 'APAC',
    description: '亞洲主要體育博彩運動資料與賠率解決方案供應商',
    why_alibaba: '亞太區部署需求；賠率 API 低延遲；多國合規需求契合 Alibaba 多區域佈局',
    estimated_arr: 250000,
    website: 'https://www.cmd368.com',
    headcount: '200+',
    tech_stack: ['AWS', 'MySQL', 'Redis'],
    contact_hint: 'CTO / Head of Engineering',
    status: 'new',
  },
  {
    company_name: 'Microgaming',
    category: 'igaming',
    region: 'Global',
    description: '曼島最老牌 iGaming 技術供應商，全球最大線上老虎機網路',
    why_alibaba: '老牌廠商雲遷移機會；亞太市場有佈局需求；大量遊戲內容 CDN 分發',
    estimated_arr: 500000,
    website: 'https://www.microgaming.co.uk',
    headcount: '1000+',
    tech_stack: ['On-prem', 'Azure partial', 'CDN'],
    contact_hint: 'CTO / Cloud Transformation Lead',
    status: 'new',
  },
  // === iGaming - Philippines (PAGCOR/POGO) ===
  {
    company_name: 'PhilWeb / PhilWeb Group',
    category: 'igaming',
    region: 'SEA',
    description: '菲律賓最大合法電子彩券與線上博彩公司，PAGCOR 授權',
    why_alibaba: '菲律賓本地合規需求；Alibaba 菲律賓 Region 優勢；高可用 DB 架構',
    estimated_arr: 300000,
    website: 'https://www.philweb.com',
    headcount: '500+',
    tech_stack: ['AWS', 'Azure', 'Oracle DB'],
    contact_hint: 'VP IT / CTO',
    status: 'new',
  },
  {
    company_name: 'Bloomberry Resorts (Solaire)',
    category: 'igaming',
    region: 'SEA',
    description: '菲律賓上市整合渡假村集團，旗下 Solaire Resort & Casino 是馬尼拉灣最大賭場',
    why_alibaba: '線上博彩系統雲化；中國VIP客戶接入優化；酒店 IT 整合雲需求',
    estimated_arr: 400000,
    website: 'https://www.bloomberryresorts.com',
    headcount: '5000+',
    tech_stack: ['On-prem', 'Azure'],
    contact_hint: 'CIO / Head of Digital',
    status: 'new',
  },
  // === iGaming - Taiwan/HK ===
  {
    company_name: 'iGaming Tech Taiwan',
    category: 'igaming',
    region: 'TW',
    description: '台灣本地 iGaming 技術服務商，提供系統整合與雲端維運服務',
    why_alibaba: '需要彈性雲資源供租用給下游客戶；Alibaba 台灣節點低延遲；合規架構諮詢',
    estimated_arr: 200000,
    website: '',
    headcount: '50+',
    tech_stack: ['AWS', 'Alibaba Cloud', 'MySQL'],
    contact_hint: 'CEO / CTO',
    status: 'new',
  },
  {
    company_name: 'Lotteries and Odds (L&O) HK',
    category: 'igaming',
    region: 'HK',
    description: '香港彩票科技公司，提供彩票管理系統與即時開獎解決方案',
    why_alibaba: '香港本地低延遲需求；Alibaba HK 節點優勢；高可用性開獎系統',
    estimated_arr: 250000,
    website: '',
    headcount: '100+',
    tech_stack: ['AWS', 'GCP', 'Redis'],
    contact_hint: 'CTO / Head of Engineering',
    status: 'new',
  },
  // === Online Gaming (non-gambling but high cloud usage) ===
  {
    company_name: 'Garena (Sea Group)',
    category: 'igaming',
    region: 'SEA',
    description: 'Free Fire 開發商，東南亞最大遊戲公司，月活玩家超 1 億',
    why_alibaba: '東南亞遊戲伺服器低延遲需求；遊戲直播 CDN；AI 反作弊需要 GPU；Alibaba SEA 節點最全',
    estimated_arr: 1500000,
    website: 'https://www.seagroup.com/garena',
    headcount: '5000+',
    tech_stack: ['AWS', 'GCP', 'Kubernetes', 'Redis'],
    contact_hint: 'VP of Engineering / Head of Cloud',
    status: 'new',
  },
  {
    company_name: 'Nexon Korea',
    category: 'igaming',
    region: 'APAC',
    description: '韓國上市大型遊戲公司，旗下 MapleStory、Dungeon&Fighter，亞太玩家為主',
    why_alibaba: '中國大陸遊戲業務需要合規雲（騰訊雲替代方案）；亞太 CDN 需求；遊戲 AI 訓練 GPU',
    estimated_arr: 1000000,
    website: 'https://company.nexon.com',
    headcount: '5000+',
    tech_stack: ['AWS', 'Tencent Cloud', 'On-prem'],
    contact_hint: 'VP of Global Infrastructure',
    status: 'new',
  },
  {
    company_name: 'Razer Gold (Razer Fintech)',
    category: 'igaming',
    region: 'SEA',
    description: 'Razer 旗下遊戲虛擬貨幣與支付平台，覆蓋東南亞 16 個市場',
    why_alibaba: '多國支付架構需要多區域雲；高可用交易系統；Alibaba Pay 整合潛力',
    estimated_arr: 400000,
    website: 'https://gold.razer.com',
    headcount: '500+',
    tech_stack: ['AWS', 'GCP', 'Kubernetes'],
    contact_hint: 'CTO / Head of Platform Engineering',
    status: 'new',
  },
  {
    company_name: 'Ubisoft Singapore',
    category: 'igaming',
    region: 'SEA',
    description: '法國遊戲巨頭 Ubisoft 新加坡工作室，負責 Skull & Bones 等大作開發',
    why_alibaba: '遊戲開發 CI/CD 需要大量算力；遊戲伺服器亞太部署；Ubisoft 有多雲策略',
    estimated_arr: 600000,
    website: 'https://www.ubisoft.com',
    headcount: '1000+',
    tech_stack: ['AWS', 'Azure', 'GCP', 'Kubernetes'],
    contact_hint: 'Head of Technical Infrastructure',
    status: 'new',
  },
  {
    company_name: 'Games Global',
    category: 'igaming',
    region: 'Global',
    description: '2022 年成立的 iGaming 內容聚合商，收購 Microgaming 遊戲庫，快速成長中',
    why_alibaba: '新公司雲原生架構機會；iGaming 內容全球 CDN；亞太市場擴張需要就近節點',
    estimated_arr: 400000,
    website: 'https://gamesglobal.com',
    headcount: '500+',
    tech_stack: ['AWS', 'Kubernetes', 'CDN'],
    contact_hint: 'CTO / VP of Engineering',
    status: 'new',
  },
  {
    company_name: 'Sportradar',
    category: 'igaming',
    region: 'Global',
    description: '全球最大體育資料供應商，為 1000+ 博彩公司提供即時賠率與運動資料',
    why_alibaba: '亞太體育資料分發需要低延遲 CDN；即時資料串流架構需要高可用；AI 預測模型需要 GPU',
    estimated_arr: 900000,
    website: 'https://www.sportradar.com',
    headcount: '3000+',
    tech_stack: ['AWS', 'Azure', 'Kafka', 'Spark'],
    contact_hint: 'CTO / Head of Cloud Platform',
    status: 'new',
  },
];
